# Generated by Django 5.2.8 on 2025-11-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_blogcategory_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='trending/')),
                ('link', models.URLField(blank=True, help_text='Link when image is clicked')),
                ('order', models.IntegerField(default=0, help_text='Order in slider (0 = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Trending Images',
                'ordering': ('order',),
            },
        ),
    ]
