# Generated by Django 5.2.8 on 2025-11-30 02:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0009_order_shipping_cost_order_shipping_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxrate",
            name="rate_percentage",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Tax rate as percentage (e.g., 17 for 17%)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
