# Generated by Django 5.2.8 on 2025-11-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0009_order_shipping_cost_order_shipping_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Show this coupon on home page"
            ),
        ),
    ]
