# Generated by Django 5.2.8 on 2025-12-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0010_alter_taxrate_rate_percentage"),
        ("ecommerce", "0010_coupon_is_featured"),
    ]

    operations = []
